name: minerva-author
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nomkl
  - numpy=1.23.2
  - pillow=9.2.0
  - flask=1.1.4
  - waitress=1.4.4
  - flask_cors=3.0.9
  - matplotlib=3.5.3
  - tifffile=2022.8.12
  - imagecodecs=2022.8.8
  - scikit-image=0.19.3
  - pandas=1.4.3
  - zarr
  - pyinstaller
  - altair
  - pip
  - pip:
      - openslide-python==1.2.0
      - ome-types==0.3.1
